### ISSUE TITLE
Translate interface to Russian

### ISSUE THREAD

**Issue by EugeneUvin** [jacquetc/skribisto#105]
Do at least basic menu translation into Russian.

src/translations (the .ts files) - use Qt Linguist to translate.

**Comment by EugeneUvin** [comment]
Hi @jacquetc can you please assign this to me? Cannot find where to participate in the project.

**Comment by jacquetc** [comment]
Russian language added Transifex [here](https://www.transifex.com/skribisto/skribisto/language/ru_RU/)

**Comment by EugeneUvin** [comment]
Hi Cyril,

I don't find the option to import ts file with translation I already did
for Ukrainian. Can you put it to transifex so I can proceed verifying it?



вс, 25 апр. 2021 г. в 20:41, Cyril Jacquet ***@***.***>:

**Comment by EugeneUvin** [comment]
Attaching it as zip as it won't attach other files and I am a bit confused about using git now.

[ukr.zip](https://github.com/jacquetc/skribisto/files/6404205/ukr.zip)

**Comment by jacquetc** [comment]
Hello,

I don't know what a new user with the translator role can do. I have this screen where I can upload translations :
![image](https://user-images.githubusercontent.com/11695581/116675702-65a66100-a9a6-11eb-9d19-267706538974.png)
at [https://www.transifex.com/skribisto/skribisto/language/uk_UA/](https://www.transifex.com/skribisto/skribisto/language/uk_UA/
)

Thank you a lot for your translation. I'm doing the upload.

Regards,
Cyril Jacquet

**Comment by jacquetc** [comment]
Russian or other languages are now using these [guidelines](https://github.com/jacquetc/skribisto#translation)

**Comment by jacquetc** [comment]
Hello, Skribisto was translated to Russian thanks to Google Translate. If you want, you can check for glaring errors ? It's quick using Transifex
