### ISSUE TITLE
Translate interface to Ukrainian

### ISSUE THREAD

**Issue by EugeneUvin** [jacquetc/skribisto#106]
Provide basic translation of menus to Ukrainian language.

src/translations (the .ts files) - use Qt Linguist to translate.

**Comment by EugeneUvin** [comment]
Hi @jacquetc please assign to me.

**Comment by EugeneUvin** [comment]
Hi @jacquetc how can I test languages after editing the file? Should I rebuild the project completely and then reinstall? I tried doing according to instruction and also just reinstalling, neither caused interface language uk_UA to appear in Settings:

```
❯ cd ~/Devel && flatpak-builder --user --repo=local-repo build-dir skribisto/package/flatpak/eu.skribisto.skribisto.yml --force-clean && flatpak install local-repo eu.skribisto.skribisto -y --reinstall
Emptying app dir 'build-dir'
Downloading sources
Fetching git repo https://github.com/jacquetc/skribisto.git, ref refs/heads/master
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
Starting build of eu.skribisto.skribisto
Cache hit for openjpeg2, skipping build
Cache hit for sqlite3, skipping build
Cache hit for quazip, skipping build
Cache hit for skribisto, skipping build
Cache hit for cleanup, skipping
Cache miss, checking out last cache hit
Finishing app
Exporting share/applications/eu.skribisto.skribisto.desktop
Exporting share/mime/packages/eu.skribisto.skribisto.xml
Exporting share/icons/hicolor/64x64/apps/eu.skribisto.skribisto.png
Exporting share/icons/hicolor/scalable/apps/eu.skribisto.skribisto.svg
Not exporting share/icons/hicolor/icon-theme.cache, wrong extension
Exporting share/icons/hicolor/128x128/apps/eu.skribisto.skribisto.png
Please review the exported files and the metadata
Committing stage finish to cache
Exporting eu.skribisto.skribisto to repo
Commit: 01b160cbc915e58e14a716ffe64d21735f21aff1d2a6be5729b86bea8d66b0ef
Metadata Total: 101
Metadata Written: 3
Content Total: 69
Content Written: 1
Content Bytes Written: 2361 (2,4 kB)
Exporting eu.skribisto.skribisto.Debug to repo
Commit: c26ca387259a10027a58dcc1ed97ac3afc43f4ab3fa5d7c5ea9251655a6930df
Metadata Total: 99
Metadata Written: 1
Content Total: 434
Content Written: 0
Content Bytes Written: 0 (0 bytes)
Pruning cache
Looking for matches…


        ID                     Ветка  Op Удалённый репозиторий Download
 1. [✗] eu.skribisto.skribisto master i  local-repo            1.0 kB / 8,7 MB

Error: Directory not empty
ошибка: Failed to установить eu.skribisto.skribisto: Directory not empty

~/Devel took 21s 
❯ flatpak install local-repo eu.skribisto.skribisto -y --reinstallLooking for matches…

eu.skribisto.skribisto permissions:
    ipc                   wayland              x11      dri
    file access [1]       dbus access [2]

    [1] host, xdg-config/kdeglobals:ro
    [2] com.canonical.AppMenu.Registrar


        ID                     Ветка  Op Удалённый репозиторий Download
 1. [✓] eu.skribisto.skribisto master i  local-repo            1.0 kB / 8,7 MB

Installation complete.

~/Devel 

```

![изображение](https://user-images.githubusercontent.com/9447963/113471061-85f40600-9462-11eb-90da-7ac519c0fd1a.png)

**Comment by jacquetc** [comment]
Hello ! To test it locally, use the yml file in skribisto/package/local/eu.skribisto.skribisto.eu


If you want to add your file, fork my project. It will appear in your Githib profile. Clone your project, modify your file, commit and push. Use the GitHub Desktop application to make these steps easier. Finally, create a Push Request in GitHub to ask me to merge you changes in my project.

Regards,
Cyril

**Comment by jacquetc** [comment]
I changed the Welcome menu yesterday. I deactivated the autoupdate of the language files because of data loss.

**Comment by jacquetc** [comment]
Hello Eugene,

Good news, it will be a lot easier for you to translate Skribisto in Ukrainian or in Russian : I just managed to set up an account on Transifex at [transifex](https://www.transifex.com/skribisto/skribisto/) . After it's done, a Push Request will be created on GitHub, I'll only have to accept the merge.

Also, Skribisto is a lot more usable now.

Regards,
Cyril Jacquet

**Comment by EugeneUvin** [comment]
Hi Cyril,

Great - I've got stuck in the mundane circle of life, it sits in the back
of my mind. I've got some draft translation and will look into transifex.

Thanks.
Eugene

вс, 25 апр. 2021 г. в 20:08, Cyril Jacquet ***@***.***>:

**Comment by EugeneUvin** [comment]
Hi Cyril,

I don't find the option to import ts file with translation I already did
for Ukrainian. Can you put it to transifex so I can proceed verifying it?

Attaching it as zip as it won't attach other files and I am a bit confused about using git now.

[ukr.zip](https://github.com/jacquetc/skribisto/files/6404226/ukr.zip)

**Comment by jacquetc** [comment]
You can see the generated push request at #122. I'll be merging it tonight since I'm doing some changes.

**Comment by EugeneUvin** [comment]
Great, thank you.

пт, 30 апр. 2021 г., 15:31 Cyril Jacquet ***@***.***>:

**Comment by jacquetc** [comment]
Hello,

Your translation was just pushed into the master branch. You can now update Skribisto. Thank you and enjoy your fine work !
