### ISSUE TITLE
No item in Help menu works

### ISSUE THREAD

**Issue by EugeneUvin** [jacquetc/skribisto#108]
None of Help menus is working right now - where they can be edited? Even "About QT" does nothing. This should be delelop branch built for Ubuntu ARM64:

https://user-images.githubusercontent.com/9447963/111471215-57232380-8731-11eb-80ef-6ed6c2bbb0d9.mp4

**Comment by jacquetc** [comment]
Hello,

It's normal since I didn't "link" the menu items to the actual Help pages. I broke this when migrating to the new UI. For now, to access help (still empty), click on the feather icon at the right of the menu and click on "Help"

**Comment by EugeneUvin** [comment]
When I click on the feather icon nothing happens - though when I hove it tip shows "Show the welcome page".

**Comment by jacquetc** [comment]
Ah, thank you for reporting this. For testing, click on the menu at right of "Chapter 2", so the page has the focus, then click again on the feather

**Comment by EugeneUvin** [comment]
Got it - still couldn't understand what id does at the moment :-)

https://user-images.githubusercontent.com/9447963/111474888-30ff8280-8735-11eb-8793-cf627ac0327f.mp4

**Comment by jacquetc** [comment]
I see that "settings" is empty, this is a bug. Try to resize the window while in it ? 
Project (maybe find a better name...) is a bit like the menu, but more adapted for touch devices. Recent projects is very useful.
Help has the bare minimum.
Example is self explanatory.

**Comment by EugeneUvin** [comment]
Summarizing: menu and icon on the top left behave unpredictably when clicked - doing nothing or opening an unexpected page.

I see "help" item now, the interface logic in not obvious here. If the UI can be adaptive I'd propose make it more native on desktop when application is on desktop. Never did QML, so not sure if it is capable of native app look for desktop, though.

Maybe Project can be renamed to a "Story" - as "storytelling" is the term that unites all kinds of stories: novels, movie scenarios etc. Though the GitHub README says this is for taking notes, too, I'd think that targeting writers as an audience would allow to reduce use cases to a smaller set that is manageable for a small project.

**Comment by jacquetc** [comment]
The native look brings more problems than solutions.
Before the UI migration, this page took all the window. It was ok then.
Now, this menu is a little page. Maybe not my best idea. I think that I'll make this page take all the window again. For the navigation in this graphical menu, I'll change the left column to : 
- New
- Load
- Examples
- Import
- Export
- Settings
- Help

Actually, I'll make it similar to MS Word 2013 menu.

Targeting only writers was what I did with Plume Creator and I realised that a lot of people used it for other things than writing stories. It's not difficult to make an UI a little more generic to please a large number of users.

**Comment by jacquetc** [comment]
Hello Eugène, 

I think the last commits resolved all the menu problems. I'm letting for now the classic menu by the Welcome menu (with Skribisto icon) because of accessibility.
