### ISSUE TITLE
Running problem 'appendScriptToLibrary'

### ISSUE THREAD

**Issue by 9acca9** [jacquetc/skribisto#11]
Hi to all.
Im having this problem. Can somebody give me a hand??

$ python setup.py
Traceback (most recent call last):
  File "setup.py", line 122, in <module>
    icon = "resources/plume-creator.png" # if you want to use an icon file, specify the file name here
TypeError: __init__() got an unexpected keyword argument 'appendScriptToLibrary'

Thanks!

**Comment by jacquetc** [comment]
Hello, setup.py is useless for now. Please use directly "python3 plume.py" and follow the steps detailed in the Readme

Regards,
Cyril
