### ISSUE TITLE
Unable to build from source on Ubuntu

### ISSUE THREAD

**Issue by xayhewalo** [jacquetc/skribisto#123]
I'm unable to build the project on Ubuntu using Qt 5.15.1, and GCC 5.3.1. I can build other QT projects with the same configuration.

I wish I had more diagnostic info but there is no read out when using build & debug

~~The console loops the following message when I try to compile on Ubuntu~~

~~WARNING: Failure to find: ../../translations/langs.qrc~~
~~WARNING: Failure to find: icons.qrc
<truncated>/Qt/5.15.1/gcc_64/bin/rcc: File does not exist '../../translations/langs.qrc'~~
~~<truncated>/Qt/5.15.1/gcc_64/bin/rcc: File does not exist 'icons.qrc'~~
~~<truncated>/Qt/5.15.1/gcc_64/bin/~~qmake -o Makefile ../../../src/app/src/src.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug~~
~~Have the `langs.qrc` and `icons.qrc` moved? I didn't find them in a brief search~~

**Comment by jacquetc** [comment]
Hello,

How are you building it ? Manually ? From Qt Creator ? Or are you following the instructions in the Readme ?

Regards, 
Cyril

**Comment by xayhewalo** [comment]
I am building and running from Qt Creator on the hope to contribute to the project

**Comment by jacquetc** [comment]
Hello,

To build it easily, I'm using these instructions (which also works for Linux) [here](https://github.com/jacquetc/skribisto#building-prerequisites). You can forgo the last step with the paths. 

Also, if you wish to contribute, you have to switch to the develop branch.

Feel free to ask if you need more help ! 

Regards,
Cyril

**Comment by xayhewalo** [comment]
I may be doing something wrong, but after following the readme trying to run the software raised "There was an error tryning to run this program"

**Comment by jacquetc** [comment]
Maybe I introduced an error in the documentation. I am using Fedora 34. Could you please give me your version of Ubuntu ?

To test it, could you also try to build Skribisto using the Flatpak method ?

**Comment by jacquetc** [comment]
The only tricky task is to not forget to set the target folder as build_skribisto_Release outside the skribisto folder. 
Ex:
/home/cyril/Devel/skribisto (git repo)
/home/cyril/Devel/build_skribisto_Release (Superbuild build directory)

Ignore any error in the Superbuild concerning Skribisto.

Did the dependencies (the Superbuild) compile well in build_skribisto_Release ?
Did Skribisto compile well using (SKR_DEV=ON) ?

I successfuly tested these steps one month ago on Fedora 33/34, Ubuntu 20.04, MacOS Big Sur (M1) and Windows 10. Maybe some steps aren't clear enough ?

**Comment by xayhewalo** [comment]
I'm using Ubunth 16.04 so maybe my system is too old. I'll try your troubleshooting steps and report back.

**Comment by jacquetc** [comment]
Hello, 

A bit old, yes. But not too old, I think.

For the Flatpak way, please try to install flatpak and flatpak-builder using these [instructions](https://flatpak.org/setup/Ubuntu/) . This PPA seems to still support Xenial. 

For the Superbuild way, Qt 5.15.2 is the only prerequisite. After you follow the steps, you can paste the whole content of your terminal in https://gist.github.com/ and share it here ?

**Comment by xayhewalo** [comment]
I think I've run into a different problems. First about not finding `hemingwaypagetoolbox.cpp` and the second about CMAKE policy CMP0017.

A truncated readout.
```
CMake Error at src/plugins/hemingwayPageToolbox/CMakeLists.txt:30 (add_library):
  Cannot find source file:

    hemingwaypagetoolbox.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc


CMake Warning (dev) in src/app/src/CMakeLists.txt:
  Policy CMP0071 is not set: Let AUTOMOC and AUTOUIC process GENERATED files.
  Run "cmake --help-policy CMP0071" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  For compatibility, CMake is excluding the GENERATED source file(s):

    "/run/build/skribisto/_flatpak_build/src/app/src/qml_SkrSettings_qml.cpp"
    "/run/build/skribisto/_flatpak_build/src/app/src/qml_MultiViewArea_qml.cpp"
    "/run/build/skribisto/_flatpak_build/src/app/src/qml_Breadcrumb_qml.cpp"
    "/run/build/skribisto/_flatpak_build/src/app/src/qml_LeftDock_qml.cpp"
    ...[a whole lot more excluded files]
```

**Comment by jacquetc** [comment]
Lol, my fault, sorry. I had a case sensitivity problem. Fixed with v1.9.16 or the latest from develop

**Comment by xayhewalo** [comment]
Here's the console out for the newest develop branch: https://gist.github.com/xayhewalo/9cb9537e4989f5b3e2c03cfa0741d4bf#file-gistfile1-txt

I should've asked this sooner, but the path to the installed application is `build-dir/export/share/applications/Skribisto`?

**Comment by jacquetc** [comment]
Ok, so you just used the Flatpak way. Flatpak apps are containerized. There is no "path" to run the app from. Use the installed desktop icon or type 'flatpak run eu.skribisto.skribisto'.  Flatpak is more used for releases. 

I'll update some steps because some are not very clear, I found out that SKR_DEV must be written in Project / "Initial CMake parameters":
-DSKR_DEV:BOOL=ON

Then click on the button "Re-configure with Initial Parameter"

![Screenshot_20210525_202708](https://user-images.githubusercontent.com/11695581/119549667-bf2c6080-bd97-11eb-8abe-53a2ca79e764.png)

**Comment by xayhewalo** [comment]
Ok I can start the program now, apologises for the hand holding

**Comment by jacquetc** [comment]
No problem ! Glad to be of help. Have fun !
