### ISSUE TITLE
UI improvements: Overview and Fullscreen

### ISSUE THREAD

**Issue by wilemrbj** [jacquetc/skribisto#19]
**Edit: Sorry I will first try version 0.67 and see how it goes, my comments were for version 0.66**

First thanks for putting efforts into writing this useful software for free. It's really useful.
Not sure if I should discuss it here but I'm using Plume to write a novel and at the moment two features are annoying me. I think that improving them would really make Plume a nice fully working software. It is those little things that usually turn people off when trying a new software, so don't dismiss these suggestions please. I wish Plume was a quality alternative for writing novels, and we are so close :)
 
**1.** The "Mise en scène" ("Overview" in english I guess) window is never well fited and it's always a pain to resize the boxes so to be able to read the captions. As the changes of size of the boxes are not saved, the trouble goes on every time you click on the Overview button.
The screenshot below has no text in it but you can see anyway that every box is too small to be read, and it stays like this even with text in it. And the "badge" boxe is always huge.
![plume-mise_en_scene](https://user-images.githubusercontent.com/34137319/48131877-db2b8d80-e291-11e8-9b3e-3cbb27290971.jpg)

**2.** The "full screen" lacks right click options like in the normal editor window, such as dictionary and styling (bold, italic...). So you can't fully work in full screen (for example highlighting words with bold for later review etc.). To correct words you need to switch between normal and full screen which is annoying. If full screen had the same features on the right click as normal screen, things would be so smooth and I would spend less time being distracted rather than writing :)

**Comment by jacquetc** [comment]
Be sure I'll not dismiss your comments. The next Plume will be based on QML where the current version is based on QWidget, so the design will differ greatly. Yet, I'm trying to keep most of the features. 

"Mise en scène" exists in the English dictionary ;-) It's a pain to adapt the columns. I don't know yet what will replace it using Qt Quick Controls 2 (see QML and Qt Quick) 

Fulllscreen mode will no longer be a separate screen, it will be the same screen, but stripped down from docks and tools, so you will have the spell checker.

**Comment by wilemrbj** [comment]
Ok I can't seem to run Plume v0.67 yet in Qt creator, because it can't import qbs. (Qtcreator is 4.2.0 on debian stretch, I don't know what's wrong, I even downloaded Qbs-dev in apt and after that also made a symlink in /usr/share to /usr/include/qbs because Qtcreator was looking in /usr/share to import qbs as far as the error console told me)...

**Comment by jacquetc** [comment]
You have to compile Plume from this repository : [https://github.com/jacquetc/plume-creator-legacy](https://github.com/jacquetc/plume-creator-legacy) from the "develop" branch . It's a QMake project.
