### ISSUE TITLE
Dropped from Ubuntu repo??

### ISSUE THREAD

**Issue by Stele77** [jacquetc/skribisto#20]
Hi!
I wanted to load plume on my Ubuntu 19.04 machine, but it seems it has been dropped..
As i am still new to the Linux world, what to do?
Can i grab the DEB file somewhere?
Can we appeal Canonicals decision somewhere? 
Thanks in advance!

**Comment by jimmysjolund** [comment]
I don't have Ubuntu installed so I can't verify. It's still in the repos for Debian 9.8 so it could be in Ubuntu still. There are deb-files for 0.66 on Sourceforge https://sourceforge.net/projects/plume-creator/files/0.6/ .

If it's dropped from Ubuntu the easiest way is to approach any of the maintainers or dev teams for an official alternative, such as Ubuntu Studio and convince them to bring it in to the repos again.

**Comment by jimmysjolund** [comment]
I just verified that plume-creator is still in Ubuntu 18.04 LTS, but not in 19.04. It's also not in Debian Testing or Unstable repos, not sure it that means it will be dropped in Debian 10 or not..?

**Comment by ParaplegicRacehorse** [comment]
Honestly, I am rapidly caring less and less about DEB, RPM, etc. Appimages work everywhere except Windows and MacOS with the added benefit of not cluttering my system with user-space applications.

Any chance of an Appimage coming soon?

**Comment by Torsten-K** [comment]
Also in Ubuntu 19.10, it isn’t available.

**Comment by AdamIsrael** [comment]
I'd advocate for a [snap](https://snapcraft.io/) package, which would make it work for most Linux distros. Same benefits as AppImage, just a different packaging format.
