### ISSUE TITLE
Old plume-creator

### ISSUE THREAD

**Issue by dulsi** [jacquetc/skribisto#3]
I continue to use the old plume-creator while you develop this one. Would you mind if I create a github repository for some fixes and perhaps put out a 0.67? I could rename the project if you are concerned with confusion with this project. If it is renamed would you like me to keep your name on the splash page?

(I don't know if I would continue to maintain the project after the new plume-creator is released. It depends on how much I like the new program.)

**Comment by jimmysjolund** [comment]
I'm not the developer but I would suggest to keep those fixes within the Plume Creator project to keep 0.66 (or later versions) in production like a community effort, at least until the new 1.5 version is release. But that's just my thoughts ...

**Comment by jacquetc** [comment]
Hello Dulsi,

Wouldn't adding the old Plume code to this Github project be better ? As a parallel "legacy" branch ? Forking is nice, but I'm not fond of dispersing this project when we are only a few developers.

More simpler : you can use the SourceForge project directly, I only have to add you to the repository. Jimmy, is it your idea ?

What do you think of it ?

**Comment by dulsi** [comment]
I wouldn't add it to this project as developers interested in the new code wouldn't have any need for the old stuff. I think it is cleaner to keep them separate.

I don't have an account with SourceForge but could create one if you are willing to add me there. Unfortunately SourceForge is down at the moment.

**Comment by jimmysjolund** [comment]
I'm not sure. On the one hand I think it would be better to have both projects in one place and with the evolution of GitHub vs SourceForge I would choose GitHub as the main source. On the other hand, as 0.66 version is already on SourceForge it could be a point to keep it there as it will go EOL (End Of Life) within a near future (unless someone picks it up to maintain).

I don't know that much on how to administer projects in GitHub but if it's easy enough to separate 0.6\* and 1.5 development I would vote for that.

**Comment by jacquetc** [comment]
After a little look around, it seems that it's preferable to separate two projects when the code base is so different.

Jimmy, thank you for your thoughts on this :-)

Dutsi, SourceForge is up now. I'll add you on the SF project the moment you create an account there. If it appears it's worthwhile to maintain old Plume after the release of Plume 1.5 / 2 ,  fork it on GitHub under a similar name. I don't know... plume-creator-legacy ? If you have questions about the code, you can write directly to me. I wish you Good Luck !

**Comment by jacquetc** [comment]
Sorry, I just realised that the dev side of SF  was down. I'm creating a repo on Github and add you to it. I recommend you follow the [git workflow](http://danielkummer.github.io/git-flow-cheatsheet/) to organize a clean repo.

**Comment by jacquetc** [comment]
Dutsi, have fun with [plume-creator-legacy](https://github.com/jacquetc/plume-creator-legacy)

**Comment by dulsi** [comment]
Oops didn't see your link to git workflow. I'm not really planning big changes in the source code so I'm not really sure it makes sense to create feature branches. My checkins have been to fix the initial dictionary choice and to fix the find and replace screen.

How do you want to handle a release? Do you want to decide when to cut a new release? Do you want to handle it? Do you want me to handle it so you can concentrate on the new code?

**Comment by jacquetc** [comment]
Sorry, for the life of me,  I can't remember if I replied to you or not. I'll assume I didn't.

I'm concentrating on the new code. You can decide to make a new release. I'm only asking you 2 things : 
- keep the versions to 0.xx
- if you modify the structure of XML in saves, warn me as I'm creating a "old project" importer for the new Plume

Thank you for your time
Cyril

**Comment by bardi9** [comment]
P.S. This was not me requesting to make another version (at least I 
don't remember asking!)...
