### ISSUE TITLE
printing

### ISSUE THREAD

**Issue by jacquetc** [jacquetc/skribisto#35]
similiar to exporting. Assemble sheets/notes, then use QWidget print dialog

**Comment by jacquetc** [comment]
don't forget a "quick print" button in edit tool box to print the current paper

**Comment by Bobpick** [comment]
I'm using 1.8.27, and there is no function to print in any screen, that is to say, I see a PRINT banner, but no way to select the printer, etc.

**Comment by jacquetc** [comment]
Hello,

No print nor export yet. It will be done shortly. Surely this weekend. Did you find any bug meanwhile ? 

Regards,
Cyril

November 20, 2020 4:50:33 PM CET Bobpick <notifications@github.com> wrote:

I'm using 1.8.27, and there is no function to print in any screen, that is to say, I see a PRINT banner, but no way to select the printer, etc.

**Comment by Bobpick** [comment]
Yes - I can't find the total word count like I used to, and when clicking where I want to edit/type it jumps around to somewhere else.
I can send an email during the weekend detailing it all - this is on the Ubuntu 20.04 machine.

**Comment by jacquetc** [comment]
Word count : for now, it's found only in the "Write" and "Project" tabs. I'll add some counter in each Sheet/Note tab soon (in the right dock)
Verify that the option "center text cursor vertically" is disabled if it bothers you

**Comment by jacquetc** [comment]
Printing added. Quick print added. Exclusion for Android
