### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by AspiredWriter** [jacquetc/skribisto#4]
Hello first let me say thank you for taking the time and putting the effort in creating a writing tool for writers.
I've been looking for years for a decent open source tool with no luck.
I wish I could help with the code but my programming skills are little more than rudimentary. I know very basic C and Excel VBA as well as a bit of JAVA and a taste of Pascal and C++. But my skills are nowhere near enough to do any kind of serious publish work. I've tried making a writing program myself but it proved too complex for me, I have neither the knowledge nor fortitude for such a project. Certainly I have no knowledge of Python which you say is the language you are using.

What I can, however, offer if you will accept is feedback as a user. I have many points, critique and ideas that might help you make this program into such a tool that will be all a writer will need (with the exception of writing skills of course). I do not want to seem judgmental or insulting so if this offer does not sit right by you, let me know and I will speak of it no more.
If, however, you value feedback in the purpose of improving your work, let me know and I will help what I can.

Once again, thank you for this program. It is not quite right yet but it has great potential.

**Comment by jimmysjolund** [comment]
I believe all feedback would be good. Then if everything is incorporated or put into backlog I don't know. I think Cyril has published books himself (?) and work with other authors as well with Plume Creator. Myself I was using Scrivener up until I found Plume Creator. Not that I am a writer ... But it was not open source and unclear about the release for linux so this project is great.

**Comment by ParaplegicRacehorse** [comment]
I didn't really feel like creating a new issue for this. I'd like to start writing some docs in wiki, or _maybe_ in a new project directory just for docs (my git-fu is weak at best), but I can't get 1.5 to compile. Followed all steps in the readme. I get this output on the command line

```
~/Programming/plume-creator$ python3 ./setup.py
Traceback (most recent call last):
  File "./setup.py", line 7, in <module>
    from cx_Freeze import setup, Executable
ImportError: No module named 'cx_Freeze'
```

Is there something I'm missing or is this an error in the project files or do I need to use `sudo`?

ubuntu 14.04. I'll update to 16.04.1 when it's released.

**Comment by jwvdveen** [comment]
@ParaplegicRacehorse 

What happens if you cd to `~/Programming/plume-creator/src/plume/` and then do `python3 plume.py`?

**Comment by jacquetc** [comment]
Hello ParaplegicRacehorse,

cx_Freeze is a python3 module, you have to install it manually with a tweak or it will crash. setup.py isn't important for now, I'll see to it later. Please launch Plume with python3 plume.py when you have the right dependencies installed. Use the develop branch of the git repo using "git checkout develop".

You can write docs in the wiki if you want, of course :-)

Regards,
Cyril

**Comment by jwvdveen** [comment]
Hi,

Last time I installed everything on my new laptop I didn't installed cx_Freeze. It's not required for executing Plume.

Perhaps remove the the installation instructions for the time being?
Since Plume is still in alpha.

Regards,
Jan-Willem

Verzonden met mijn Windows Phone

---

Van: Cyril Jacquetmailto:notifications@github.com
Verzonden: ‎4-‎6-‎2016 11:55
Aan: jacquetc/plume-creatormailto:plume-creator@noreply.github.com
CC: jwvdveenmailto:jwvdveen@outlook.com; Commentmailto:comment@noreply.github.com
Onderwerp: Re: [jacquetc/plume-creator] Feedback (#4)

Hello ParaplegicRacehorse,

cx_Freeze is a python3 module, you have to install it manually with a tweak or it will crash. setup.py isn't important for now, I'll see to it later. Please launch Plume with python3 plume.py when you have the right dependencies installed. Use the develop branch of the git repo using "git checkout develop".

You can write docs in the wiki if you want, of course :-)

Regards,
Cyril

---

**Comment by ParaplegicRacehorse** [comment]
@jacquetc running straight from `[...]/plume-creator/src` works well. And, yep, this is clearly alpha. I think I'll write the docs in Plume 0.6 since this version is clearly unusable. Watch for a pull request from me, soon, with new directory /docs. Where in the code should I go look for command line arguments, which seems a reasonable place to start.

**Comment by ParaplegicRacehorse** [comment]
@jacquetc, would you put up a roadmap for what you intend to include it upcoming release versions? It will help quite a lot in establishing a roadmap for a manual, as well as in filing feature request issues. There are several things I want to see in a program of this sort, some of which are not found even in commercial offerings.

**Comment by jacquetc** [comment]
Hello, I'll try to come up with a sort of roadmap. The first goal is to deliver the same basic features than the old Plume. I'll write again tomorrow. No deadline, only a wish to show the first release in july. What sort of features are you thinking about ?

**Comment by ParaplegicRacehorse** [comment]
That's a pretty long list. We can start with a feature I never tried to see whether was in legacy versions = import of reference material and/or media files. Importing files, in general, is a big item on my wishlist. There are a variety of filetypes I'd like to be able to add to a project. And exporting/building, too. I thought styles were handled incorrectly in older versions = bold, italic, etc should actually be defined in the style and not rely on authors remember to apply them on the fly. I'd like to the see the chapter list sidebar turned drag-and-drop so I don't have to forever up/down arrow to move a section around. Etc, etc. I imagine most of the import/export stuff can most easily be done with plugins. Other items on my wishlist are probably best done in core.

**Comment by jacquetc** [comment]
Sorry, I don't understand your "reference material". Do you mean websites, pdf, .doc,  photos and such ? I'll not be able to import text from .doc file in Plume, we will have to copy/paste from LibreOffice or another office software. 
My intention is to manage lists of files in a Binder panel, all of which will be opened in external software.

Using bold, strike must be available manually, but it will be added to the overall style.

Drag-drop : sure, like in the old Plume.

**Comment by jwvdveen** [comment]
@jacquetc,  the same basic features as the old Plume with a refreshing new GUI. This would be great as a teaser/demo for (future) users. Something we have and a glimpse of things to come.

The bold and italic etc can be done manually, but it might be interesting to think about to let those be defined by some sort of template. Do you want to write a novel? Headers and titles are predefined. Do you want to write some manual, adding bold an italic etc might be better done manually.

Just an idea though...

**Comment by jacquetc** [comment]
What headers, what titles ? :-) Only when exporting to .odt or printing would the user able to define their format.

**Comment by ParaplegicRacehorse** [comment]
> Sorry, I don't understand your "reference material". Do you mean websites, pdf, .doc, photos and such ? I'll not be able to import text from .doc file in Plume, we will have to copy/paste from LibreOffice or another office software. 
> My intention is to manage lists of files in a Binder panel, all of which will be opened in external software.

Is that what the Binder is for? Perfect!

> Drag-drop : sure, like in the old Plume.

This doesn't work for me in 0.66.1 but I vaguely remember it working in previous versions.

> Using bold, strike `[...]` the overall style.
> 
> What headers, what titles ? :-) Only when exporting to .odt or printing would the user able to define their format.

On the surface, these two statements conflict. I believe @jwvdveen intended for "Headers and Titles" would be text style-names defined in the styles manager.

Another note on styles - why limit them to text? Why not go all out with CSS-type defines? Granted, that's only easy to do with HTML export, but there's no particular reason why it couldn't be extended to other exports, though I'm pretty sure mobi, azw and epub don't support that type of thing well. PDF does, though.

What is the planned document "compile", or export, backend and which formats are you planning out-of-the-box?

**Comment by jacquetc** [comment]
Headers and Titles : I don't see where in Plume will titles be used. The tree structure is providing titles.

I will not support export to epub, mobi or others . Only to HTML, .odt and plain text (what Qt library is providing). Plus CSV for data, maybe. Plume is a writing software, not fit for publishing. The export system will be plugin-friendly, so one would be able to have fun creating such feature :-) Other software are doing much better : Calibre, LibreOffice,...

**Comment by ruckustboom** [comment]
> I will not support export to epub, mobi or others . Only to HTML, .odt and plain text

I assume this means no built-in export for PDF as well? I find it useful to have PDF backups of drafts as I go. Will this have to be done externally or implemented in a plugin?

**Comment by ParaplegicRacehorse** [comment]
> Headers and Titles : I don't see where in Plume will titles be used. The tree structure is providing titles.

Titles and headers, in this reference, are text styles. Like

```
# This is a Title, and

### This is a Header.
```

> I assume this means no built-in export for PDF as well

I imagine it would be fairly easy for someone versed in python to write an export plugin to pipe through [pandoc](http://pandoc.org/) or some other document parser. I was thinking it would be super-cool to export into a [Scribus](http://scribus.net/) document, which might take quite a lot more coding expertise but would allow for really easy layout adjustment and tweaking before compiling into PDF. :smile:

**Comment by jacquetc** [comment]
(writing from my phone)
Actually, I remember now Qt being able to "print" to PDF. Which old Plume was doing. Be careful, Plume will be cross-platform and Pandoc is Linux-only. But piping is a good idea...

**Comment by jacquetc** [comment]
Scribus : Depends on the format. Sometimes, basic documents are easy to create, then the targeted software complexes it. See basic HTML against what you see on the internet.
I'll create a useable API to navigate Plume project content, so everyone can create plugins.

**Comment by ruckustboom** [comment]
Speaking of Scribus, does anyone know where to get the post 1.5 file format specs? I can only fine 1.4 and earlier.

**Comment by jimmysjolund** [comment]
Pandoc is cross platform: http://pandoc.org/installing.html

**Comment by jacquetc** [comment]
@jimmysjolund Ah, sorry I didn't know. 
If the user installs pandoc, then plugins would be able to use it directly.

@t-boom PDF writing is directly handled by Qt

**Comment by ruckustboom** [comment]
Good to know (I don't have much experience with Qt)
