### ISSUE TITLE
error: org.kde.Platform/x86_64/5.15 not installed

### ISSUE THREAD

**Issue by magicvince** [jacquetc/skribisto#75]
I'm using LMDE4 (Linux Mint Debian Edition, based on debian 10) and when I try to compil, I've this error 

error: org.kde.Platform/x86_64/5.15 not installed

After running

flatpak-builder --user --repo=local-repo build-dir skribisto/eu.skribisto.skribisto.yml --force-clean

flatpak install flathub org.kde.Sdk//5.15 is done

**Comment by jacquetc** [comment]
Hello,
I'm not a Flatpak specialist, so I certainly forgot something in the instructions. I'm using Manjaro with KDE (Arch based) . Are you using the 32bit or 64bit version of LMDE4 ? I'm installing it in a VM to test the installation

**Comment by jacquetc** [comment]
Found the culprit !
Please type in the console :
flatpak install flathub org.kde.Platform//5.15
then : 
flatpak-builder --user --repo=local-repo build-dir skribisto/eu.skribisto.skribisto.yml --force-clean

I'll update the doc. Thank you to  have reported this !

**Comment by jacquetc** [comment]
Also, use these commands once when in ~/Devel
flatpak build-update-repo local-repo
flatpak --user remote-add --no-gpg-verify local-repo local-repo

then, try to install Skribisto

**Comment by magicvince** [comment]
Sorry for long time to react.  It's in progress but at the end of the compilation an error occured:
`========================================================================
Building module skribisto in /home/magicvince/Dev/.flatpak-builder/build/skribisto-1
========================================================================
Already on 'master'
-- Found Git: /usr/bin/git (found version "2.29.0") 
-- [MunkeiVersionFromGit] Version: 1.8.19
     Git tag:     [v1.8.19]
     Git hash:    []
     Decorated:   [v1.8.19]
     Identifiers: []
     Metadata:    []
     SemVer:      [1.8.19]
-- The CXX compiler identification is GNU 10.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Installing in /app. Run /run/build/skribisto/_flatpak_build/prefix.sh to set the environment for skribisto.
CMake Error at src/libskribisto-data/src/CMakeLists.txt:13 (find_package):
  By not providing "FindQuaZip-Qt5.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "QuaZip-Qt5", but CMake did not find one.

  Could not find a package configuration file provided by "QuaZip-Qt5" with
  any of the following names:

    QuaZip-Qt5Config.cmake
    quazip-qt5-config.cmake

  Add the installation prefix of "QuaZip-Qt5" to CMAKE_PREFIX_PATH or set
  "QuaZip-Qt5_DIR" to a directory containing one of the above files.  If
  "QuaZip-Qt5" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/run/build/skribisto/_flatpak_build/CMakeFiles/CMakeOutput.log".
Error: module skribisto: Le processus fils s’est terminé avec le code 1`

I try to use your next command

flatpak build-update-repo local-repo

Have an other error

error: /home/magicvince/Dev/skribisto/Devel/local-repo: opendir(/home/magicvince/Dev/skribisto/Devel/local-repo): Aucun fichier ou dossier de ce type

May I have to rename part of the command?

Thanks for your help

**Comment by jacquetc** [comment]
Hello, 
I'm testing it on my LMDE4 virtual machine and its compiling fine. It's weird because quazip 1.1 is compiled and installed before Skribisto compilation.
Older versions of quazip use another system and isn't supported by Plume anymore.  

Can you send to me the complete console output ?
Please delete completly  the folder "Devel" in ~/Dev/skribisto/ . It's in the wrong place.

Then, do these commands (I adapted them to your system):
cd ~/Dev
git clone https://github.com/jacquetc/skribisto.git
flatpak-builder --user --repo=local-repo build-dir skribisto/eu.skribisto.skribisto.yml --force-clean
flatpak build-update-repo local-repo
flatpak --user remote-add --no-gpg-verify local-repo local-repo
flatpak install eu.skribisto.skribisto -y --reinstall


Normally, a "local-repo" folder must appear in Dev.
Later, when a new version is out, do ;
cd ~/Dev && flatpak-builder --user --repo=local-repo build-dir skribisto/eu.skribisto.skribisto.yml --force-clean && flatpak install eu.skribisto.skribisto -y --reinstall

Regards,
Cyril

**Comment by jacquetc** [comment]
No answer, closing the issue

**Comment by magicvince** [comment]
Sorry for my test lag.

here's my log

mylogin@desk:~/Dev$ flatpak-builder --user --repo=local-repo build-dir skribisto/package/flatpak/eu.skribisto.skribisto.yml --force-clean
Downloading sources
Fetching git repo https://github.com/jacquetc/skribisto.git, ref refs/heads/master
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
Starting build of eu.skribisto.skribisto
Cache hit for openjpeg2, skipping build
Cache hit for sqlite3, skipping build
Cache hit for quazip, skipping build
Cache hit for skribisto, skipping build
Cache hit for cleanup, skipping
Cache hit for finish, skipping
Everything cached, checking out from cache
Exporting eu.skribisto.skribisto to repo
error: Writing content object: min-free-space-percent '3%' would be exceeded, at least 114,7 kB requested
Export failed: Le processus fils s’est terminé avec le code 1

thnaks for your attention

**Comment by jacquetc** [comment]
Hello,

You are out of space. I recommend that you remove all folders in  ~/Dev/.flatpak-builder/build :
`rm -fr  ~/Dev/.flatpak-builder/build/*`
If not already done, type : `rm -fr   ~/Dev/skribisto/Devel`
Earlier versions of my Flatpak manifest is cluttering space. It was fixed. 

Regards,
Cyril

**Comment by magicvince** [comment]
So sorry Cyril I don't understand why the build failed again and again on one of my computer … because I try on my second machine (LMDE4 too) and it works.
I'll try many stupid things (like cloning my build directory for the working computer to the other). In vain. Every time and different steps the build failed with Exporting eu.skribisto.skribisto to repo
error: Writing content object: min-free-space-percent '3%' would be exceeded, at least 114,7 kB requested
Export failed: Le processus fils s’est terminé avec le code 1

So I could work with skribisto on my second computer it's a first good news. I'll should try later on the first one. But I'll think the problem isn't the code but some invisble old set-up  (for me) on my computer

**Comment by jacquetc** [comment]
Well, I had this exact same problem. Type `df -h` to check your free space on your hard disk. Clearing  ~/Dev/.flatpak-builder/build/ helped me greatly. If it's not enough, you can do a bit of cleaning in your documents.
You have to regain 3% at minimum.

**Comment by magicvince** [comment]
I'm so heavy … 

compilation step seems to be ok after cleaning my home 
next command seems to be ok too 

> magicvince@desk: ~/Devel$ flatpak build-update-repo local-repo
Updating appstream branch
Extracting icons for component eu.skribisto.skribisto
Updating summary

… Have some hope

>magicvince@desk:~/Devel$ flatpak --user remote-add --no-gpg-verify local-repo local-repo
error: Remote local-repo already exists

(event if rm -rf ~/Devel  and retry all the process from git clone)
I'm sad, but hope it's a minor error and try the next command

>magicvince@desk:~/Devel$ flatpak install local-repo eu.skribisto.skribisto -y --reinstall
Looking for matches…
error: Unable to load summary from remote local-repo: Remote listing for local-repo not available; server has no summary file. Check the URL passed to remote-add was valid.

I'm trying the update command but the result is the same.
So easy on my second computer, so hard on this one … sorry for my insistance.
Very very thanks to help me to understand

**Comment by jacquetc** [comment]
No worries :-) Since you started again from a clean state, I think you only have to type : 
```
cd ~Devel
flatpak build-update-repo local-repo
flatpak --user remote-add --no-gpg-verify local-repo local-repo
flatpak install local-repo eu.skribisto.skribisto -y --reinstall
```

**Comment by magicvince** [comment]
Ok I finish to find the solution with your help and flatpak documentation

Retyping your command have the same result at this steps : 

>magicvince@desk:~/Devel$ flatpak --user remote-add --no-gpg-verify local-repo local-repo
error: Remote local-repo already exists

The solution was to delete the existing remote local-repo

>magicvince@desk:~/Devel$ flatpak remotes  
This list the remotes and specialy this line

local-repo           user,no-gpg-verify

So I delete this repo with the flatpak command

>magicvince@desk:~/Devel$ flatpak remote-delete local-repo 

and redo

>magicvince@desk:~/Devel$ flatpak --user remote-add --no-gpg-verify local-repo local-repo
then
magicvince@desk:~/Devel$ flatpak install local-repo eu.skribisto.skribisto -y --reinstall

And the install is ok

Thanks
