### ISSUE TITLE
Can't parse skribisto.yml

### ISSUE THREAD

**Issue by Bobpick** [jacquetc/skribisto#88]
This is the error I get when trying to install:

bob@bob:~/Devel$ flatpak-builder --user --repo=local-repo build-dir skribisto/eu.skribisto.skribisto.yml --force-clean
Can't parse 'skribisto/eu.skribisto.skribisto.yml': <data>:1:6: Parse error: unexpected identifier `app-id', expected value

Any suggestions?

**Comment by jacquetc** [comment]
Hello,
I think you need to upgrade your flatpak package to the latest. What is you version ? (flatpak -v) What is your system ?

**Comment by Bobpick** [comment]
I am on Ubuntu 18.04, and the Flatpak version is 1.0.9
Sorry.

**Comment by jacquetc** [comment]
I'm discovering that Flatpak understands the .yml files only recently.  see [here](https://github.com/Stremio/stremio-bugs/issues/167).  and [here](https://github.com/flatpak/flatpak-builder/issues/2)
JSON was used bedore.

Two choices are yours : 
- download, build, install the last flatpak-builder [here](https://github.com/flatpak/flatpak-builder/releases/download/1.0.11/flatpak-builder-1.0.11.tar.xz)
-- tar -xJf flatpak-builder-1.0.11.tar.xz
-- in the folder : ./configure
-- make
-- sudo make install
-- and I hope that you have all the dependencies !

- other choice : convert my .yml in .json
-- using [this converter](https://onlineyamltools.com/convert-yaml-to-json), convert my yml file to JSON. Result [here](https://pastebin.com/kkZP4ajG)
- create a eu.skribisto.skribisto.json file with the content pasted in it, by the eu.skribisto.skribisto.yml file in the skribisto root folder
- replace yml by json in my commands

tell me if it runs !

**Comment by Bobpick** [comment]
I did the 2nd choice, and it ran until I get to the step:
flatpak install eu.skribisto.skribisto -y --reinstall

Which is the last command to install the program.

**Comment by jacquetc** [comment]
Just to precise things : did it install or not ?

**Comment by Bobpick** [comment]
Precisely, yes, the steps you gave me worked fine.
The last step did not. Should i open a separate ticket for that?

**Comment by jacquetc** [comment]
No no, the same ticket is fine. I would need more information. Do you havé any output ?

**Comment by jacquetc** [comment]
For your information, Ubuntu 20.04.1 is the latest LTS. Maybe is it time for an upgrade ? I'm myself on the latest Fedora and I'm quite happy with the stability and Gnome 3 is finally becoming usable and useful. Use VirtualBox to test it before ?

**Comment by jacquetc** [comment]
I managed to install Skribisto on Ubuntu 18.4. 
Changes : I firstly converted the yml to json. Lastly, I added "local-repo" to the install command

From a clean install, all the commands are :

sudo apt install flatpak-builder -y
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.kde.Sdk//5.15
flatpak install flathub org.kde.Platform//5.15
mkdir ~/Devel
cd ~/Devel
git clone https://github.com/jacquetc/skribisto.git
flatpak-builder --user --repo=local-repo build-dir skribisto/eu.skribisto.skribisto.json --force-clean
flatpak build-update-repo local-repo
flatpak --user remote-add --no-gpg-verify local-repo local-repo
flatpak install local-repo eu.skribisto.skribisto -y --reinstall

Please tell me how it's doing. 
Regards

**Comment by Bobpick** [comment]
> For your information, Ubuntu 20.04.1 is the latest LTS. Maybe is it time for an upgrade ? I'm myself on the latest Fedora and I'm quite happy with the stability and Gnome 3 is finally becoming usable and useful. Use VirtualBox to test it before ?

To be honest, on my 20.04 LTS system the program is very disappointing.  Once I get this resolved I"ll be able to send you those issues. It won't import a *.plume file. But more later.

**Comment by Bobpick** [comment]
> I managed to install Skribisto on Ubuntu 18.4.
> Changes : I firstly converted the yml to json. Lastly, I added "local-repo" to the install command
> 
> From a clean install, all the commands are :
> 
> sudo apt install flatpak-builder -y
> flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
> flatpak install flathub org.kde.Sdk//5.15
> flatpak install flathub org.kde.Platform//5.15
> mkdir ~/Devel
> cd ~/Devel
> git clone https://github.com/jacquetc/skribisto.git
> flatpak-builder --user --repo=local-repo build-dir skribisto/eu.skribisto.skribisto.json --force-cley an
> flatpak build-update-repo local-repo
> flatpak --user remote-add --no-gpg-verify local-repo local-repo
> flatpak install local-repo eu.skribisto.skribisto -y --reinstall
> 
> Please tell me how it's doing.
> Regards

Okay, this worked like a champ. I was actually able to "import" my work from Plume, however, there is NOTHING there. 
If I try any of the snippets I had, they are completely blank in Skrib. 
I stopped using Plume because all of a sudden nothing would be displayed and yet when I export it, all of the material is still there, and the Plume file size is correct.

**Comment by jacquetc** [comment]
Great !
For your import problem, it interests me since I only can test the import from my own .plume project files. Would you be willing to send me your .plume for me to fix Skribisto's importer ? cyril.jacquet@skribisto.eu
For your information, I just released 1.8.25

**Comment by jacquetc** [comment]
> > For your information, Ubuntu 20.04.1 is the latest LTS. Maybe is it time for an upgrade ? I'm myself on the latest Fedora and I'm quite happy with the stability and Gnome 3 is finally becoming usable and useful. Use VirtualBox to test it before ?
> 
> To be honest, on my 20.04 LTS system the program is very disappointing. Once I get this resolved I"ll be able to send you those issues. It won't import a *.plume file. But more later.

Thank you for your honesty :-) The problem I have with working on Skribisto alone is that I am my own critic. And I'm crap at styling. As you can see in the list in the readme, the program isn't finished yet and I'm open to make changes.

**Comment by Bobpick** [comment]
I've sent you the file. I noticed that the yml/json isn't in the flatpak directory so I had to move a copy over for the update to take place, but it's going now.

**Comment by jacquetc** [comment]
Fixed !
Thank you for your help !
Do a "git pull" in your Skribisto folder.
You will find both JSON and YML files in package/flatpak
Importing may take a few long seconds, to be fixed later

**Comment by jacquetc** [comment]
Sorry, not fixed yet. You are using the separators (option that I never used), I'm working around that then I push a new version

**Comment by jacquetc** [comment]
v1.8.27 is now available :-) You can try it

**Comment by Bobpick** [comment]
Okay, everything works on the 18.04 machine, and I think with the changes you made this should all be good. Thanks for the help.
