### ISSUE TITLE
Import folders full of files

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [jacquetc/skribisto#9]
## What

Ability to import folders full of files, particularly markup files (rst, markdown, whatever), would be tremendously useful for the documentation project.
#### Reason

One of the best things that came with [Scrivener](https://www.literatureandlatte.com/scrivener.php) was an interactive tutorial in the form of a Scrivener project. I intend to create a similar document for Plume, but it will be un-diff-able in git if it's only available as a Plume project.
#### Also

Exporting the Plume project as a folder full of files would be handy if I choose to edit the documentation, especially the interactive tutorial, with Plume.

**Comment by jacquetc** [comment]
Ultimately, Plume will support a "git-able" project structure, where files will be humanly readable thanks to Markdown or Txt2tags. To quicken the development of the GUI, I'm using SQLite as project file for now.

One of the difficulty to overcome is the translation from HTML to Text2tags/Markdown. Or more specifically, a parser from Markdown to QTextDocument.

**Comment by ParaplegicRacehorse** [comment]
> a parser from Markdown to QTextDocument.

That may be more trouble than it's worth, particularly since Markdown syntax is so fragmented between flavors. I assume QTextDocument takes some form of xml input? Could you from Markdown/reST/whatever to DocBook xml and import that?

**Comment by jacquetc** [comment]
Qt's QTextDocument can import plain text and a sort-of HTML. I'm playing with pandoc for now. I would have wanted to avoid the convert part completely to avoid loss.
